### ISSUE TITLE
Any plan for supporting Data Streams websocket mehtods ?

### ISSUE THREAD

**Issue by diogopublio** [Jakenberg/binance-ruby#17]
Any plan for supporting Data Streams websocket mehtods ?

**Comment by Jakenberg** [comment]
Yes, I need this myself. I will update you here once I have published a solution. You are welcome to create a PR as well. I will certainly review it promptly.

**Comment by Jakenberg** [comment]
I was mistaken. I've already implemented the methods needed for data streams. They are [here](https://github.com/Jakenberg/binance-ruby/blob/master/lib/binance/api/data_stream.rb). You can find binance documentation regarding how to properly use these methods [here](https://binance-docs.github.io/apidocs/spot/en/#user-data-streams).

You are free to use whatever WebSocket API wrapper you would like, although I recommend [faye-websocket-ruby](https://github.com/faye/faye-websocket-ruby).

Cheers!

**Comment by Jakenberg** [comment]
Good news! Data Streams are now available through this library. Example can be found [here](https://github.com/Jakenberg/binance-ruby#websocket-example).
