### ISSUE TITLE
Use quoteOrderQty in new Order

### ISSUE THREAD

**Issue by cristianogregnanin** [Jakenberg/binance-ruby#19]
In the source code I don't find the possibility to use the ```quoteOrderQty``` when I create new order and I want to buy with ```market``` type.

https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#new-order--trade

It is normal?

**Comment by rafapolo** [comment]
have you tried? Works for me. It is normal because creating an Order.create! you pass whatever param to the Binance API. It doesnt have to be in the source code.

**Comment by cristianogregnanin** [comment]
> have you tried? Works for me. It is normal because creating an Order.create! you pass whatever param to the Binance API. It doesnt have to be in the source code.

```Binance::Api::Order.create!(side: 'BUY', symbol: 'BTCUSDT', type: 'MARKET', quoteQrderQty: '5', test: true)```
```ArgumentError (unknown keyword: :quote_order_qty)```

```Binance::Api::Order.create!(side: 'BUY', symbol: 'BTCUSDT', type: 'MARKET', quote_order_qty: '5', test: true)```
```ArgumentError (unknown keyword: :quote_order_qty)```

**Comment by rafapolo** [comment]
Not able to test here now, but almost sure I've used it as :quoteOrderQty

**Comment by rafapolo** [comment]
Uhm. I see what you mean. I'm not sure if I was confused on my previous comment, since I also have used craysiii/binance gem
Wouldn't you consider to improve it and do a pull request?

**Comment by cristianogregnanin** [comment]
> Uhm. I see what you mean. I'm not sure if I was confused on my previous comment, since I also have used craysiii/binance gem
> Wouldn't you consider to improve it and do a pull request?

Yes, I grave already improved And tester in my fork. In next few day I Will male a pull request

**Comment by Jakenberg** [comment]
Very much appreciate your contribution @cristianogregnanin! It will be available in `v1.1`.
