### ISSUE TITLE
does this really work for US?

### ISSUE THREAD

**Issue by jtoy** [Jakenberg/binance-ruby#21]
I couldnt get it to work with ruby, but the python bindings worked perfectly.
This code dies on ruby but same exact thing with same keys/ip works fine with python:
require 'binance-ruby'
BINANCE_TLD = "US"
puts Binance::Api.ping!
puts Binance::Api::Account.info!

error:  (-2015) Invalid API-key, IP, or permissions for action. (Binance::Api::Error)

im fairly certain it is not working under US tld.

**Comment by jtoy** [comment]
I found the bug, the README is wrong, the function tld is never called and so BINANCE_TLD is also never read. So it looks like no one is using this For US.

**Comment by Jakenberg** [comment]
I am using this gem for the US.

The error suggests that you might be trying to use non-US api keys for requests. You need to create a new set of API keys on the binance.us site, then use those keys instead.

**Comment by Jakenberg** [comment]
btw, there is a how-to on USA accounts: https://github.com/jakenberg/binance-ruby#accounts-in-the-usa

please let me know if there are errors anywhere in those docs and i'll get them updated. 

Thank you for using/contributing!
