### ISSUE TITLE
Always getting error code -1104

### ISSUE THREAD

**Issue by gafemoyano** [Jakenberg/binance-ruby#3]
Hi,

Thanks for providing a great gem to interact with the Binance API.
Do you guys have any idea why I might be getting the response "{"code":-1104,"msg":"Not all sent parameters were read; read '6' parameter(s) but was sent '7'."}" on all the user requests that I've beent trying to make?

Thank you for your help.

**Comment by Jakenberg** [comment]
@gafemoyano You're welcome! Sorry to hear the troubles...

What method are you getting this error on exactly? Also, what are you sending (or not sending) as arguments to that method? Either would be helpful to seeing what's going on. 

FYI that error code is [from binance API](https://github.com/binance-exchange/binance-official-api-docs/blob/master/errors.md#-1104-unread_parameters).

**Comment by gafemoyano** [comment]
This was an error on my part from sending a parameter with the wrong name. Binance API would then receive 7 parameters, but only read 6 of them. 

I'll close this now, thank you again for this gem!
