### ISSUE TITLE
timeInForce

### ISSUE THREAD

**Issue by dpblnt** [Jakenberg/binance-ruby#7]
Hi there, i'm stuck at the beginning of things, need a bit of a help.
```ruby
new_order = Binance::Api::Order::create!(symbol: pair, side: 'BUY' , type: 'LIMIT', price: buyPrice,  quantity: amount)
```
results
```bash
/usr/local/lib64/ruby/gems/2.3.0/gems/binance-ruby-0.1.9/lib/binance/api/request.rb:42:in `process!': (-1102) Mandatory parameter 'timeInForce' was not sent, was empty/null, or malformed. (Binance::Api::Error)
```
but
```ruby
new_order = Binance::Api::Order::create!(symbol: pair, side: 'BUY' , type: 'LIMIT', price: buyPrice,  quantity: amount, timeInForce: 'GTC')
```
results
```bash
/usr/local/lib64/ruby/gems/2.3.0/gems/binance-ruby-0.1.9/lib/binance/api/order.rb:35:in `create!': unknown keyword: timeInForce (ArgumentError)
```

**Comment by Jakenberg** [comment]
Ahoy! 🚢 

To immediately resolve the issue you will need to snake case the `timeInForce` argument in your call to `create!` (i.e. `time_in_force`).

After seeing this issue, I realized that binance API errors showing parameters in camelcase isn't consistent with how this gem requires that parameters be in snake case. So I updated the gem as such to make it more intuitive. You can read more about the `0.2` release [here](https://github.com/Jakenberg/binance-ruby/releases/tag/0.2).

Apologies for any inconvenience!
