### ISSUE TITLE
How to quick buy a specific coin?

### ISSUE THREAD

**Issue by tannguyen** [Jakenberg/binance-ruby#8]
I would like to buy a coin with my all current btc as fast as possible, I would like to know if we can do it with only 1 API call. The approach I'm using it we request to get the current price first, then calculate the quantity, then create an order based on that. Btw it will takes 2 API calls.

How can I achieve it by using only 1 API call, (the API to get current price will take about > 1sec).

**Comment by Jakenberg** [comment]
What you're describing is at the binance API level. I personally think its important that you make the two api calls. I don't know of a way to use the binance API in a way that would let you achieve two for one. I will close as it's off topic for this gem.
